# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\code\pypaint\mainwindow.ui',
# licensing of 'd:\code\pypaint\mainwindow.ui' applies.
#
# Created: Mon Oct 14 21:11:31 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_cydPaintBoard(object):
    def setupUi(self, cydPaintBoard):
        cydPaintBoard.setObjectName("cydPaintBoard")
        cydPaintBoard.resize(432, 440)
        self.centralwidget = QtWidgets.QWidget(cydPaintBoard)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(60, 0))
        self.toolBox.setObjectName("toolBox")
        self.toolPen = QtWidgets.QPushButton(self.toolBox)
        self.toolPen.setGeometry(QtCore.QRect(0, 0, 25, 25))
        self.toolPen.setMouseTracking(True)
        self.toolPen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/pen"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolPen.setIcon(icon)
        self.toolPen.setCheckable(True)
        self.toolPen.setObjectName("toolPen")
        self.line_2 = QtWidgets.QFrame(self.toolBox)
        self.line_2.setGeometry(QtCore.QRect(0, 230, 61, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtWidgets.QLabel(self.toolBox)
        self.label_3.setGeometry(QtCore.QRect(0, 270, 31, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.toolBox)
        self.label_4.setGeometry(QtCore.QRect(30, 270, 31, 16))
        self.label_4.setObjectName("label_4")
        self.lColor = QtWidgets.QPushButton(self.toolBox)
        self.lColor.setGeometry(QtCore.QRect(0, 240, 25, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lColor.sizePolicy().hasHeightForWidth())
        self.lColor.setSizePolicy(sizePolicy)
        self.lColor.setStyleSheet("background-color: #000000")
        self.lColor.setText("")
        self.lColor.setObjectName("lColor")
        self.rColor = QtWidgets.QPushButton(self.toolBox)
        self.rColor.setGeometry(QtCore.QRect(30, 240, 25, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rColor.sizePolicy().hasHeightForWidth())
        self.rColor.setSizePolicy(sizePolicy)
        self.rColor.setStyleSheet("background-color:#FFFFFF")
        self.rColor.setText("")
        self.rColor.setObjectName("rColor")
        self.toolLine = QtWidgets.QPushButton(self.toolBox)
        self.toolLine.setGeometry(QtCore.QRect(30, 30, 25, 25))
        self.toolLine.setMouseTracking(True)
        self.toolLine.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/line"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolLine.setIcon(icon1)
        self.toolLine.setCheckable(True)
        self.toolLine.setObjectName("toolLine")
        self.toolRec = QtWidgets.QPushButton(self.toolBox)
        self.toolRec.setGeometry(QtCore.QRect(0, 60, 25, 25))
        self.toolRec.setMouseTracking(True)
        self.toolRec.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/rec"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolRec.setIcon(icon2)
        self.toolRec.setCheckable(True)
        self.toolRec.setObjectName("toolRec")
        self.toolCircle = QtWidgets.QPushButton(self.toolBox)
        self.toolCircle.setGeometry(QtCore.QRect(30, 60, 25, 25))
        self.toolCircle.setMouseTracking(True)
        self.toolCircle.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/circle"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolCircle.setIcon(icon3)
        self.toolCircle.setCheckable(True)
        self.toolCircle.setObjectName("toolCircle")
        self.toolBucket = QtWidgets.QPushButton(self.toolBox)
        self.toolBucket.setGeometry(QtCore.QRect(0, 30, 25, 25))
        self.toolBucket.setMouseTracking(True)
        self.toolBucket.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/bucket"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBucket.setIcon(icon4)
        self.toolBucket.setCheckable(True)
        self.toolBucket.setObjectName("toolBucket")
        self.toolRubber = QtWidgets.QPushButton(self.toolBox)
        self.toolRubber.setGeometry(QtCore.QRect(30, 0, 25, 25))
        self.toolRubber.setMouseTracking(True)
        self.toolRubber.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/rubber"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolRubber.setIcon(icon5)
        self.toolRubber.setCheckable(True)
        self.toolRubber.setObjectName("toolRubber")
        self.lineEdit = QtWidgets.QLineEdit(self.toolBox)
        self.lineEdit.setGeometry(QtCore.QRect(0, 310, 51, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.toolBox)
        self.label.setGeometry(QtCore.QRect(0, 290, 54, 12))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.toolBox)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMouseTracking(True)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 337, 375))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.board = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.board.setGeometry(QtCore.QRect(0, 0, 121, 131))
        self.board.setMouseTracking(True)
        self.board.setText("")
        self.board.setObjectName("board")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        cydPaintBoard.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(cydPaintBoard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 432, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        cydPaintBoard.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(cydPaintBoard)
        self.statusbar.setObjectName("statusbar")
        cydPaintBoard.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(cydPaintBoard)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(cydPaintBoard)
        self.actionSave.setObjectName("actionSave")
        self.actionNew = QtWidgets.QAction(cydPaintBoard)
        self.actionNew.setObjectName("actionNew")
        self.actionChange_Board_Size = QtWidgets.QAction(cydPaintBoard)
        self.actionChange_Board_Size.setObjectName("actionChange_Board_Size")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuEdit.addAction(self.actionChange_Board_Size)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(cydPaintBoard)
        QtCore.QMetaObject.connectSlotsByName(cydPaintBoard)

    def retranslateUi(self, cydPaintBoard):
        cydPaintBoard.setWindowTitle(QtWidgets.QApplication.translate("cydPaintBoard", "MainWindow", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("cydPaintBoard", "Left", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("cydPaintBoard", "Right", None, -1))
        self.lineEdit.setText(QtWidgets.QApplication.translate("cydPaintBoard", "(0-50)", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("cydPaintBoard", "Size:", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("cydPaintBoard", "File", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("cydPaintBoard", "Edit", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("cydPaintBoard", "Open", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("cydPaintBoard", "Save", None, -1))
        self.actionNew.setText(QtWidgets.QApplication.translate("cydPaintBoard", "New", None, -1))
        self.actionChange_Board_Size.setText(QtWidgets.QApplication.translate("cydPaintBoard", "Change Board Size", None, -1))

import paint_rc
